#pragma once

#ifdef RING0
#include <ntifs.h>
#else
#include <windows.h>
#endif // RING0

#define CD_IOCTL_SET_TARGET_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0X800, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#define CD_IOCTL_COLLECT_PROCESS_INFO CTL_CODE(FILE_DEVICE_UNKNOWN, 0X801, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define CD_IOCTL_COLLECT_OBJECT_TYPE_INFO CTL_CODE(FILE_DEVICE_UNKNOWN, 0X802, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define CD_IOCTL_COLLECT_PROCESS_DETAIL CTL_CODE(FILE_DEVICE_UNKNOWN, 0X803, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define CD_IOCTL_COLLECT_OBJECT_TYPE_DETAIL CTL_CODE(FILE_DEVICE_UNKNOWN, 0X804, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)