#pragma once
#ifdef RING0
#include <ntifs.h>
#else
#include <windows.h>
#endif // RING0

#define UD_IOCTL_SET_TARGET_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0X800, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#define UD_IOCTL_MDL_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0X801, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define UD_IOCTL_MDL_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0X802, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#define UD_IOCTL_PHYSICAL_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0X803, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define UD_IOCTL_PHYSICAL_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0X804, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#define UD_IOCTL_CR3_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0X805, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define UD_IOCTL_CR3_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0X806, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#define UD_IOCTL_TERMINATE_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0X807, METHOD_IN_DIRECT, FILE_ANY_ACCESS)