#pragma once

#include <QtWidgets/QWidget>
#include "ProcessDetailWndUI.h"
#include <Windows.h>

#define EPROCESS_DETAIL_PROPERTY_INDEX 0
#define EPROCESS_DETAIL_VALUE_INDEX 1

#define EPROCESS_DETAIL_PROPERTY_COUNT 17
#define EPROCESS_DETAIL_PROPERTY_PEPROCESS_NAME "Eprocess"
#define EPROCESS_DETAIL_PROPERTY_UNIQUE_PROCESS_ID_NAME "UniqueProcessId"
#define EPROCESS_DETAIL_PROPERTY_CREATE_TIME_NAME "CreateTime"
#define EPROCESS_DETAIL_PROPERTY_PEAK_VIRTUAL_SIZE_NAME "PeakVirtualSize"
#define EPROCESS_DETAIL_PROPERTY_VIRTUAL_SIZE_NAME "VirtualSize"
#define EPROCESS_DETAIL_PROPERTY_MM_RESERVED_NAME "MmReserved"
#define EPROCESS_DETAIL_PROPERTY_COOKIE_NAME "Cookie"
#define EPROCESS_DETAIL_PROPERTY_OWNER_PROCESS_ID_NAME "OwnerProcessId"
#define EPROCESS_DETAIL_PROPERTY_DEBUG_PORT_NAME "DebugPort"
#define EPROCESS_DETAIL_PROPERTY_PRIORITY_CLASS_NAME "PriorityClass"
#define EPROCESS_DETAIL_PROPERTY_SECURITY_PORT_NAME "SecurityPort"
#define EPROCESS_DETAIL_PROPERTY_VAD_HINT_NAME "VadHint"
#define EPROCESS_DETAIL_PROPERTY_VAD_COUNT_NAME "VadCount"
#define EPROCESS_DETAIL_PROPERTY_VAD_PHYSICAL_PAGES_NAME "VadPhysicalPages"
#define EPROCESS_DETAIL_PROPERTY_VAD_PHYSICAL_PAGES_LIMIT_NAME "VadPhysicalPagesLimit"
#define EPROCESS_DETAIL_PROPERTY_SECURITY_DOMAIN_NAME "SecurityDomain"
#define EPROCESS_DETAIL_PROPERTY_PARENT_SECURITY_DOMAIN_NAME "ParentSecurityDomain"

#define PCB_DETAIL_PROPERTY_INDEX 0
#define PCB_DETAIL_VALUE_INDEX 1

#define PCB_DETAIL_PROPERTY_COUNT 8
#define PCB_DETAIL_PROPERTY_PPCB_NAME "Pcb"
#define PCB_DETAIL_PROPERTY_DIRECTORY_TABLE_BASE_NAME "DirectoryTableBase"
#define PCB_DETAIL_PROPERTY_KERNEL_TIME_NAME "KernelTime"
#define PCB_DETAIL_PROPERTY_USER_TIME_NAME "UserTime"
#define PCB_DETAIL_PROPERTY_READY_TIME_NAME "ReadyTime"
#define PCB_DETAIL_PROPERTY_USER_DIRECTORY_TABLE_BASE_NAME "UserDirectoryTableBase"
#define PCB_DETAIL_PROPERTY_KERNEL_WAIT_TIME_NAME "KernelWaitTime"
#define PCB_DETAIL_PROPERTY_USER_WAIT_TIME_NAME "UserWaitTime"

#define PEB_DETAIL_PROPERTY_INDEX 0
#define PEB_DETAIL_VALUE_INDEX 1

#define PEB_DETAIL_PROPERTY_COUNT 10
#define PEB_DETAIL_PROPERTY_PPEB_NAME "Peb"
#define PEB_DETAIL_PROPERTY_INHERITED_ADDRESS_SPACE_NAME "InheritedAddressSpace"
#define PEB_DETAIL_PROPERTY_BEING_DEBUGGED_NAME "BeingDebugged"
#define PEB_DETAIL_PROPERTY_IMAGE_BASE_ADDRESS_NAME "ImageBaseAddress"
#define PEB_DETAIL_PROPERTY_PROCESS_HEAP_NAME "ProcessHeap"
#define PEB_DETAIL_PROPERTY_SYSTEM_RESERVED_NAME "SystemReserved"
#define PEB_DETAIL_PROPERTY_NUMBER_OF_PROCESSORS_NAME "NumberOfProcessors"
#define PEB_DETAIL_PROPERTY_NUMBER_OF_HEAPS_NAME "NumberOfHeaps"
#define PEB_DETAIL_PROPERTY_MAXIMUM_NUMBER_OF_HEAPS_NAME "MaximumNumberOfHeaps"
#define PEB_DETAIL_PROPERTY_SESSION_ID_NAME "SessionId"

class ProcessDetailWnd : public QWidget {
    Q_OBJECT

private:
    Ui::ProcessDetailWndClass m_Ui;

    PVOID m_pEprocess;

public:
    ProcessDetailWnd(PVOID pEprocess, QWidget* parent = nullptr);
    ~ProcessDetailWnd();

private:
    void RefershProcessDetail(bool checked = false);
};